name: Test

permissions:
  contents: write

on:
  pull_request:
  workflow_dispatch:

jobs:
  format:
    name: auto format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git switch ${{ env.CURRENT_BRANCH }}
      - uses: fregante/setup-git-user@v2
      - run: cargo fmt --all
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git commit -am "Automated changes"
          git push origin ${{ env.CURRENT_BRANCH }}

  test:
    name: cargo test
    runs-on: ubuntu-latest
    needs: format
    if: ${{ needs.format.outputs.modified != 'true' }} # 如果 format 的输出中没有修改，执行 test
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall -y --no-symlinks cargo-nextest
      - name: Setup sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo nextest run && cargo test -p bpm --doc
