name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: "test setup browser"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install chromium
        run: sudo apt-get install chromium-browser
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python main.py
